config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get "/requests/search" => "requests#search"
  resources :requests

end

app/models/request.rb
class Request < ActiveRecord::Base


  validates :name, presence: {message: "Must enter a name" }

  validates :email, presence: true

  validates :department, presence: true

  validates :message, presence: true

  def self.search(search)
    where("name ILIKE :word OR email ILIKE :word OR department ILIKE :word OR message ILIKE :word", {word: "%#{search}%"})
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def index
    @requests = Request.all
  end

  def new
    @request = Request.new
  end

  def create
    request_params = params.require(:request).permit(:name, :email, :department, :message)
    @request = Request.new request_params
    if @request.save
      redirect_to request_path(@request)
    else
      render :new
    end
  end

  def show
    @request = Request.find params[:id]
  end

  def search
    if params[:search]
      @requests = Request.all.search(params[:search])
    else
      @requests = Request.all.order('created_at DESC')
    end
  end

  def edit
    @request = Request.find params[:id]
  end

  def update
    @request = Request.find params[:id]
    request_params = params.require(:request).permit(:name, :email, :department)
    @request = Request.new request_params
    if @request.save
      redirect_to request_path(@request)
    else
      render :new
    end

  end

  def destroy
    @request = Request.find params[:id]
    @request.destroy
    redirect_to requests_path
  end

  def done
    @request = Request.find(params[:request_id])
    @request.done = 'true'
    save
    redirect_to request_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/home/index.html.erb
<h1>Supporter</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "Add New Request", new_request_path %>
  |
  <%= link_to "Display All Requests", requests_path %>
<%= yield %>

</body>
</html>

app/views/requests/edit.html.erb
<h1>Edit Support Request</h1>

<div>
  <%= @request.errors.full_messages.join(', ') %>
</div>

<%= form_for @request do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.radio_button :department, 'Sales' %>
    <%= label :department_sales, 'Sales' %>
    <%= f.radio_button :department, 'Marketing' %>
    <%= label :department_marketing, 'Marketing' %>
    <%= f.radio_button :department, 'Technical' %>
    <%= label :department_technical, 'Technical' %>
  </div>

  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>
  <%= f.submit "Save" %>
<% end %>

app/views/requests/index.html.erb
<h1>Support Requests</h1>

<div class="search">
<%= form_tag(requests_path, :method => "get") do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>
</div>

<br>
<%# if @requests.present? %>
  <%#= render @requests %>
<%# else %>
  <!-- <p>Sorry, we could not find what you were looking for...</p> -->
<%# end %>

<table>
  <thead>
  <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Department</th>
      <th>Message</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.name %></td>
        <td><%= request.email %></td>
        <td><%= request.department %></td>
        <td><%= request.message %></td>
        <td><%= link_to "Edit", edit_request_path(request) %> <%= link_to "Delete", request, method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<% @requests %>

app/views/requests/new.html.erb
<h1>New Support Request</h1>

<div>
  <%= @request.errors.full_messages.join(', ') %>
</div>

<%= form_for @request do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.radio_button :department, 'Sales' %>
    <%= label :department_sales, 'Sales' %>
    <%= f.radio_button :department, 'Marketing' %>
    <%= label :department_marketing, 'Marketing' %>
    <%= f.radio_button :department, 'Technical' %>
    <%= label :department_technical, 'Technical' %>
  </div>

  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>
  <%= f.submit "Save" %>
<% end %>

app/views/requests/search.html.erb
<h1>Search Results</h1>

<div class="search">
<%= form_tag(requests_search_path, :method => "get") do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>
</div>

<br>
<%# if @requests.present? %>
  <%#= render @requests %>
<%# else %>
  <!-- <p>Sorry, we could not find what you were looking for...</p> -->
<%# end %>

<table>
  <thead>
  <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Department</th>
      <th>Message</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.name %></td>
        <td><%= request.email %></td>
        <td><%= request.department %></td>
        <td><%= request.message %></td>
        <td><%= link_to "Edit", edit_request_path(request) %> <%= link_to "Delete", request, method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/requests/show.html.erb
<h1>Thank you for your request!</h1>